font_family Source Code Pro

cursor_shape block

mouse_hide_wait -1

repaint_delay 6
sync_to_monitor yes

enable_audio_bell no
bell_on_tab "*meow* "

tab_bar_edge bottom
tab_bar_style powerline
tab_bar_align left
tab_bar_show_new_tab_button no
tab_bar_min_tabs 2

inactive_tab_foreground #000000
progress_bar bottom

cursor_trail 1
cursor_trail_decay 0 0.1
cursor_trail_color

scrollbar never

pixel_scroll yes

window_padding_width 2
window_resize_step_cells 1
window_resize_step_lines 1
window_border_width 1
draw_minimal_borders yes

draw_window_borders_for_single_window no

active_border_color #ffffff
inactive_border_color #303030
bell_border_color #ff0000

tab_powerline_style slanted

foreground #eeeeee

background_opacity 1.0

background_image /home/briella/Pictures/Wallpapers/Darkest Hour.jpg
background_image_layout cscaled

background_tint 0.87

selection_foreground none
selection_background none

shell_integration enabled

notify_on_cmd_finish unfocused 2 notify
